// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/prd_management","parentId":"@@/global-layout","id":"1"},"2":{"path":"/login","layout":false,"id":"2"},"3":{"path":"/generate_cases","parentId":"@@/global-layout","id":"3"},"4":{"path":"/definition_api","parentId":"@@/global-layout","id":"4"},"5":{"path":"/prd_management","parentId":"@@/global-layout","id":"5"},"6":{"path":"/sprint_management","parentId":"@@/global-layout","id":"6"},"7":{"path":"/plan_management","parentId":"@@/global-layout","id":"7"},"8":{"path":"/create_plan","parentId":"@@/global-layout","id":"8"},"9":{"path":"/prompt_management","parentId":"@@/global-layout","id":"9"},"10":{"path":"/data_prepare","parentId":"@@/global-layout","id":"10"},"11":{"path":"/ai_chat","parentId":"@@/global-layout","id":"11"},"12":{"path":"/sprint_statics","parentId":"@@/global-layout","id":"12"},"13":{"path":"/review_prds","parentId":"@@/global-layout","id":"13"},"14":{"path":"/review_prds_detail/:id","parentId":"@@/global-layout","id":"14"},"15":{"path":"/review_cases","parentId":"@@/global-layout","id":"15"},"16":{"path":"/review_cases_ms","parentId":"@@/global-layout","id":"16"},"17":{"path":"/review_cases_ms_detail/:id","parentId":"@@/global-layout","id":"17"},"18":{"path":"/llm_management","parentId":"@@/global-layout","id":"18"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__generate_cases__index" */'@/pages/generate_cases/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__definition_api__index" */'@/pages/definition_api/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__prd_management__index" */'@/pages/prd_management/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__sprint_management__index" */'@/pages/sprint_management/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__plan_management__index" */'@/pages/plan_management/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__plan_management__createPlan" */'@/pages/plan_management/createPlan.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__prompt_management__index" */'@/pages/prompt_management/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__data_prepare__index" */'@/pages/data_prepare/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__ai_chat__index" */'@/pages/ai_chat/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__sprint_statics__index" */'@/pages/sprint_statics/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__review_prds__index" */'@/pages/review_prds/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__review_prds__detail" */'@/pages/review_prds/detail.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__review_cases__index" */'@/pages/review_cases/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__review_cases_ms__index" */'@/pages/review_cases_ms/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__review_cases_ms__detail" */'@/pages/review_cases_ms/detail.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__llm_management__index" */'@/pages/llm_management/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/root/qa-center-web/src/layouts/index.tsx')),
},
  };
}
