"""add_new_fields

Revision ID: 49c56e9f0533
Revises: 
Create Date: 2024-09-25 13:03:11.190664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49c56e9f0533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_history')
    op.drop_table('test_case_copy1')
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.String(length=255), nullable=True))

    with op.batch_alter_table('data_prepare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sheet_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rule_row', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('generated_data_abnormal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('creator', sa.String(length=255), nullable=True))
        batch_op.drop_column('file_name')
        batch_op.drop_column('oss_path')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('large_language_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('remark', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default', sa.Integer(), nullable=True))
        batch_op.drop_column('simple_name')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.drop_constraint('nodes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sprint', ['sprint_id'], ['id'])

    with op.batch_alter_table('product_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_issues', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('creator', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('product_files_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sprint', ['sprint_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tester', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('jira_project_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('jira_board_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confluence_space_key', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Integer(), nullable=True))

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.String(length=255), nullable=True))
        batch_op.alter_column('precondition',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('test_case_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nodes', ['node_id'], ['id'])
        batch_op.create_foreign_key(None, 'sprint', ['sprint_id'], ['id'])
        batch_op.drop_column('steps')
        batch_op.drop_column('expect_result')

    with op.batch_alter_table('test_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('test_plan_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sprint', ['sprint_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_plan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('test_plan_ibfk_1', 'sprint', ['sprint_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_column('creator')

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expect_result', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True))
        batch_op.add_column(sa.Column('steps', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('test_case_ibfk_1', 'sprint', ['sprint_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('precondition',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=True)
        batch_op.drop_column('creator')

    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('confluence_space_key')
        batch_op.drop_column('jira_board_name')
        batch_op.drop_column('jira_project_key')
        batch_op.drop_column('tester')

    with op.batch_alter_table('product_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_files_ibfk_1', 'sprint', ['sprint_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_column('creator')
        batch_op.drop_column('review_issues')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('nodes_ibfk_1', 'sprint', ['sprint_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.drop_column('position')

    with op.batch_alter_table('large_language_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('simple_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True))
        batch_op.drop_column('default')
        batch_op.drop_column('remark')
        batch_op.drop_column('company')

    with op.batch_alter_table('data_prepare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('oss_path', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('file_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True))
        batch_op.drop_column('creator')
        batch_op.drop_column('generated_data_abnormal')
        batch_op.drop_column('rule_row')
        batch_op.drop_column('sheet_name')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('creator')

    op.create_table('test_case_copy1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('priority', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('precondition', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True),
    sa.Column('description', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('steps', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('expect_result', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True),
    sa.Column('sprint_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('node_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint.id'], name='test_case_copy1_ibfk_1', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('llm_history',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('llm_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ask', mysql.TEXT(), nullable=True),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('create_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
